// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fake.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lprotobuf {

  /// <summary>Holder for reflection information generated from fake.proto</summary>
  public static partial class FakeReflection {

    #region Descriptor
    /// <summary>File descriptor for fake.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FakeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpmYWtlLnByb3RvEglscHJvdG9idWYiHAoETmVzdBIJCgFBGAEgASgIEgkK",
            "AUIYAiABKAkijwEKCFVzZXJkYXRhEgkKAUEYASABKA0SCQoBQhgCIAEoBBIJ",
            "CgFDGAMgASgCEhoKAUQYBCABKAsyDy5scHJvdG9idWYuTmVzdBIJCgFGGAUg",
            "AygJEgkKAUUYBiADKAUiMAoCRTISCAoETm9uZRAAEgkKBUZpcnN0EAESCgoG",
            "U2Vjb25kEAISCQoFVGhpcmQQAyowCgJFMRIICgROb25lEAASCQoFRmlyc3QQ",
            "ChIKCgZTZWNvbmQQAhIJCgVUaGlyZBAFQhFaDy4uL2x1YV9wcm90b2J1ZmIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Lprotobuf.E1), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Lprotobuf.Nest), global::Lprotobuf.Nest.Parser, new[]{ "A", "B" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Lprotobuf.Userdata), global::Lprotobuf.Userdata.Parser, new[]{ "A", "B", "C", "D", "F", "E" }, null, new[]{ typeof(global::Lprotobuf.Userdata.Types.E2) }, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum E1 {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("First")] First = 10,
    [pbr::OriginalName("Second")] Second = 2,
    [pbr::OriginalName("Third")] Third = 5,
  }

  #endregion

  #region Messages
  public sealed partial class Nest : pb::IMessage<Nest> {
    private static readonly pb::MessageParser<Nest> _parser = new pb::MessageParser<Nest>(() => new Nest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Nest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lprotobuf.FakeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Nest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Nest(Nest other) : this() {
      a_ = other.a_;
      b_ = other.b_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Nest Clone() {
      return new Nest(this);
    }

    /// <summary>Field number for the "A" field.</summary>
    public const int AFieldNumber = 1;
    private bool a_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool A {
      get { return a_; }
      set {
        a_ = value;
      }
    }

    /// <summary>Field number for the "B" field.</summary>
    public const int BFieldNumber = 2;
    private string b_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string B {
      get { return b_; }
      set {
        b_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Nest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Nest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (A != other.A) return false;
      if (B != other.B) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (A != false) hash ^= A.GetHashCode();
      if (B.Length != 0) hash ^= B.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (A != false) {
        output.WriteRawTag(8);
        output.WriteBool(A);
      }
      if (B.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(B);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (A != false) {
        size += 1 + 1;
      }
      if (B.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(B);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Nest other) {
      if (other == null) {
        return;
      }
      if (other.A != false) {
        A = other.A;
      }
      if (other.B.Length != 0) {
        B = other.B;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            A = input.ReadBool();
            break;
          }
          case 18: {
            B = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Userdata : pb::IMessage<Userdata> {
    private static readonly pb::MessageParser<Userdata> _parser = new pb::MessageParser<Userdata>(() => new Userdata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Userdata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lprotobuf.FakeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Userdata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Userdata(Userdata other) : this() {
      a_ = other.a_;
      b_ = other.b_;
      c_ = other.c_;
      d_ = other.d_ != null ? other.d_.Clone() : null;
      f_ = other.f_.Clone();
      e_ = other.e_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Userdata Clone() {
      return new Userdata(this);
    }

    /// <summary>Field number for the "A" field.</summary>
    public const int AFieldNumber = 1;
    private uint a_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint A {
      get { return a_; }
      set {
        a_ = value;
      }
    }

    /// <summary>Field number for the "B" field.</summary>
    public const int BFieldNumber = 2;
    private ulong b_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong B {
      get { return b_; }
      set {
        b_ = value;
      }
    }

    /// <summary>Field number for the "C" field.</summary>
    public const int CFieldNumber = 3;
    private float c_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float C {
      get { return c_; }
      set {
        c_ = value;
      }
    }

    /// <summary>Field number for the "D" field.</summary>
    public const int DFieldNumber = 4;
    private global::Lprotobuf.Nest d_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Lprotobuf.Nest D {
      get { return d_; }
      set {
        d_ = value;
      }
    }

    /// <summary>Field number for the "F" field.</summary>
    public const int FFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_f_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> f_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> F {
      get { return f_; }
    }

    /// <summary>Field number for the "E" field.</summary>
    public const int EFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_e_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> e_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> E {
      get { return e_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Userdata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Userdata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (A != other.A) return false;
      if (B != other.B) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(C, other.C)) return false;
      if (!object.Equals(D, other.D)) return false;
      if(!f_.Equals(other.f_)) return false;
      if(!e_.Equals(other.e_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (A != 0) hash ^= A.GetHashCode();
      if (B != 0UL) hash ^= B.GetHashCode();
      if (C != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(C);
      if (d_ != null) hash ^= D.GetHashCode();
      hash ^= f_.GetHashCode();
      hash ^= e_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (A != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(A);
      }
      if (B != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(B);
      }
      if (C != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(C);
      }
      if (d_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(D);
      }
      f_.WriteTo(output, _repeated_f_codec);
      e_.WriteTo(output, _repeated_e_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (A != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(A);
      }
      if (B != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(B);
      }
      if (C != 0F) {
        size += 1 + 4;
      }
      if (d_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(D);
      }
      size += f_.CalculateSize(_repeated_f_codec);
      size += e_.CalculateSize(_repeated_e_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Userdata other) {
      if (other == null) {
        return;
      }
      if (other.A != 0) {
        A = other.A;
      }
      if (other.B != 0UL) {
        B = other.B;
      }
      if (other.C != 0F) {
        C = other.C;
      }
      if (other.d_ != null) {
        if (d_ == null) {
          D = new global::Lprotobuf.Nest();
        }
        D.MergeFrom(other.D);
      }
      f_.Add(other.f_);
      e_.Add(other.e_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            A = input.ReadUInt32();
            break;
          }
          case 16: {
            B = input.ReadUInt64();
            break;
          }
          case 29: {
            C = input.ReadFloat();
            break;
          }
          case 34: {
            if (d_ == null) {
              D = new global::Lprotobuf.Nest();
            }
            input.ReadMessage(D);
            break;
          }
          case 42: {
            f_.AddEntriesFrom(input, _repeated_f_codec);
            break;
          }
          case 50:
          case 48: {
            e_.AddEntriesFrom(input, _repeated_e_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Userdata message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum E2 {
        [pbr::OriginalName("None")] None = 0,
        [pbr::OriginalName("First")] First = 1,
        [pbr::OriginalName("Second")] Second = 2,
        [pbr::OriginalName("Third")] Third = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
